# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 02:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en_US', 'English'), ('zh_HK', '中文'), ('zh_CN', '官话'), ('de_DE', 'Deutsch')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='runner',
            name='raceno',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
